
# Main executable
add_executable(smart_home_exec src/main.cpp)
target_include_directories(smart_home_exec PRIVATE ${PROJECT_ROOT}/include)
target_sources(smart_home_exec PRIVATE
        src/utils/to_lower.cpp
        src/utils/to_upper.cpp
        src/utils/OnOff.cpp
        src/utils/getCurrentTimestamp.cpp
        src/utils/SimpleJson/parse.cpp
        src/utils/SimpleJson/stringify.cpp
        src/utils/SimpleJson/constructor.cpp
        src/utils/SimpleJson/getString.cpp
        src/utils/SimpleJson/getInt.cpp
        src/utils/to_upper.cpp
        src/utils/trim.cpp
        src/utils/getPort.cpp
        src/utils/getExecutableDir.cpp
        src/utils/getHostIp.cpp
        src/utils/OnOff.cpp
        src/utils/to_lower.cpp
        src/ParserResult/to_string.cpp
        src/Logger/error.cpp
        src/Logger/destructor.cpp
        src/Logger/constructor.cpp
        src/Logger/info.cpp
        src/Logger/fatal.cpp
        src/HttpClient/destructor.cpp
        src/HttpClient/constructor.cpp
        src/HttpClient/post.cpp
        src/HttpClient/get.cpp
        src/Devices/Device/sendCommand.cpp
        src/Devices/Device/constructor.cpp
        src/Devices/Device/getRemoteState.cpp
        src/Devices/Device/setRemoteState.cpp
        src/Devices/Device/getHealth.cpp
        src/Devices/WebEnabledDevice/getRemoteState.cpp
        src/Devices/WebEnabledDevice/destructor.cpp
        src/Devices/WebEnabledDevice/constructor.cpp
        src/Devices/WebEnabledDevice/setRemoteState.cpp
        src/Devices/WebEnabledDevice/getHealth.cpp
        src/Devices/Controllers/Lights/constructor.cpp
        src/Devices/Controllers/Lights/destructor.cpp
        src/Devices/Controllers/Lights/exists.cpp
        src/Devices/Controllers/Lights/turnOff.cpp
        src/Devices/Controllers/Lights/turnOn.cpp
        src/Devices/Controllers/Lights/getDeviceState.cpp
        src/Devices/Controllers/Lights/sendCommand.cpp
        src/Devices/Controllers/Lights/updateDeviceState.cpp
        src/Devices/Controllers/Television/getDeviceState.cpp
        src/Devices/Controllers/Television/volume.cpp
        src/Devices/Controllers/Television/channel.cpp
        src/Devices/Controllers/Television/sendCommand.cpp
        src/Devices/Controllers/Television/constructor.cpp
        src/Devices/Controllers/Television/updateDeviceState.cpp
        src/Devices/Controllers/Thermostat/setTemp.cpp
        src/Devices/Controllers/Thermostat/getDeviceState.cpp
        src/Devices/Controllers/Thermostat/heat.cpp
        src/Devices/Controllers/Thermostat/sendCommand.cpp
        src/Devices/Controllers/Thermostat/constructor.cpp
        src/Devices/Controllers/Thermostat/getTemp.cpp
        src/Devices/Controllers/Thermostat/fanOn.cpp
        src/Devices/Controllers/Thermostat/cool.cpp
        src/Devices/Controllers/Thermostat/fanOff.cpp
        src/Devices/Controllers/Thermostat/ThermostatMode.cpp
        src/Devices/Controllers/Thermostat/updateDeviceState.cpp
        src/Devices/Controllers/Security/getDeviceState.cpp
        src/Devices/Controllers/Security/sendCommand.cpp
        src/Devices/Controllers/Security/constructor.cpp
        src/Devices/Controllers/Security/updateDeviceState.cpp
        src/Devices/Controllers/Vacuum/getDeviceState.cpp
        src/Devices/Controllers/Vacuum/sendCommand.cpp
        src/Devices/Controllers/Vacuum/constructor.cpp
        src/Devices/Controllers/Vacuum/updateDeviceState.cpp
        src/Devices/Factory/create.cpp
        src/CommandShell/destructor.cpp
        src/CommandShell/Run.cpp
        src/CommandShell/displayWelcome.cpp
        src/CommandShell/constructor.cpp
        src/CommandParser/invoke_device.cpp
        src/CommandParser/parse.cpp
        src/CommandParser/tokenize.cpp
        src/CommandParser/destructor.cpp
        src/CommandParser/constructor.cpp
        src/CommandType/identifyCommand.cpp
        src/CommandType/to_string.cpp
        src/Help/showHelp.cpp
        src/Help/getSmartRemark.cpp
)
